dist: trusty
language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

script:
  # Run unit testing
  - ./gradlew test

  # Run performance testing
  - ./gradlew performanceTest --stacktrace --info